version: '2'

services:
  db:
     image: postgres
     ports:
         - "5432:5432"

  web:
     build: ./store
     user: root
     command: bash -c "python3 manage.py bower_install &&  python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
     volumes:
          - ./store:/code
     expose:
          - "8000"
     depends_on:
          - db
  nginx:
     image: nginx:latest
     ports:
         - "8000:8000"
     volumes:
         - ./nginx/config:/etc/nginx/conf.d
     depends_on:
         - web
